name: Tests

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/acceptance-tests.yml'
  workflow_dispatch:

jobs:
  go-tests:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Run tests
        run: go test ./...

  acceptance-tests:
    name: Acceptance tests (${{ matrix.cli }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        cli: [vault, bao]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Install Vault binary
        uses: eLco/setup-vault@v1
        if: ${{ matrix.cli == 'vault' }}
      - name: Install OpenBao binary
        if: ${{ matrix.cli == 'bao' }}
        run: |
          wget -nv -O ${{ runner.temp }}/bao_2.0.0_linux_amd64.deb https://github.com/openbao/openbao/releases/download/v2.0.0/bao_2.0.0_linux_amd64.deb
          sudo dpkg -i ${{ runner.temp }}/bao_2.0.0_linux_amd64.deb
      - name: Run Vault Dev server
        if: ${{ matrix.cli == 'vault' }}
        run: |
          docker run --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=root' -d --rm --name=dev-vault -p 8200:8200 hashicorp/vault
          export VAULT_SERVER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' dev-vault)
          echo "VAULT_ADDR=http://$VAULT_SERVER_IP:8200" >> "$GITHUB_ENV"
          echo "VAULT_TOKEN=root" >> "$GITHUB_ENV"
      - name: Run Bao Dev server
        if: ${{ matrix.cli == 'bao' }}
        run: |
          docker run --cap-add=IPC_LOCK -e 'BAO_DEV_ROOT_TOKEN_ID=root' -d --rm --name=dev-bao -p 8200:8200 quay.io/openbao/openbao server -dev
          export VAULT_SERVER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' dev-bao)
          echo "VAULT_ADDR=http://$VAULT_SERVER_IP:8200" >> "$GITHUB_ENV"
          echo "VAULT_TOKEN=root" >> "$GITHUB_ENV"
      - name: Create Artifactory data directories and copy config
        run: |
          mkdir -p ${{ runner.temp }}/artifactory/var/etc
          cp ${{ github.workspace }}/scripts/system.yaml ${{ runner.temp }}/artifactory/var/etc/system.yaml
          sudo chown -R 1030:1030 ${{ runner.temp }}/artifactory/var
      - name: Run Artifactory container
        id: run_artifactory_container
        run: |
          ARTIFACTORY_VERSION=$(awk -F: '/FROM/ {print $2}' scripts/Dockerfile)
          echo "Start up Artifactory container"
          docker run -i --name artifactory -d --rm \
            -v ${{ runner.temp }}/artifactory/var:/var/opt/jfrog/artifactory \
            -e JF_SHARED_DATABASE_ALLOWNONPOSTGRESQL=true \
            -p 8081:8081 -p 8082:8082 \
            releases-docker.jfrog.io/jfrog/artifactory-jcr:${ARTIFACTORY_VERSION}
          echo "Set localhost to a container IP address, since we run docker inside of docker"
          export LOCALHOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' artifactory)
          export JFROG_URL="http://${LOCALHOST}:8082"
          echo "JFROG_URL=$JFROG_URL" >> "$GITHUB_ENV"
          echo "Waiting for Artifactory services to start at ${JFROG_URL}"
          until curl -sf -o /dev/null -m 5 -u admin:password "${JFROG_URL}/artifactory/api/system/ping/"; do
            printf '.'
            sleep 5
          done
          echo "Waiting for Artifactory UI to start"
          until curl -sf -o /dev/null -m 5 -u admin:password "${JFROG_URL}/ui/login/"; do
            printf '.'
            sleep 5
          done
          export JFROG_ACCESS_TOKEN=$(JFROG_URL="${JFROG_URL}" TOKEN_USERNAME=vault-admin scripts/getArtifactoryAdminToken.sh)
          echo "::add-mask::$JFROG_ACCESS_TOKEN"
          echo "JFROG_ACCESS_TOKEN=$JFROG_ACCESS_TOKEN" >> "$GITHUB_ENV"
      - name: Execute all tests
        run: make alltests
      - name: Clean up Docker container
        if: always() && steps.run_artifactory_container.outcome == 'success'
        run: docker stop artifactory
